# -*- coding: utf-8 -*-

from openerp import models, fields

# This model is used to store information about SSH keys generated by us,
# which sometimes are uploaded to cloud providers to access the nodes.
# So, sometimes code and cloud_id will be null (if key was not uploaded)
class Key(models.Model):
    _name = 'unison.key'
    _order = 'name'

    code = fields.Char('Code') # DigitalOcean code, assigned after create
    name = fields.Char('Name', required=True, index=True)
    cloud_id = fields.Many2one('unison.cloud', 'Cloud', ondelete='restrict')
    fingerprint = fields.Char('Fingerprint')
    public_key = fields.Text('Public Key')
    private_key = fields.Text('Private Key (Linux)')
    putty_key = fields.Text('Private Key (PuTTY)')
    notes = fields.Text('Notes')
    active = fields.Boolean('Active', default=True)

    _sql_constraints = [
        ('fingerprint_uniq', 'unique(fingerprint)', 'A key with same fingerprint exists'),
    ]

    # Reverse relationships
    nodes = fields.One2many('unison.node', 'key_id', 'Nodes')

